name: pages_deploy
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ghostscript
        run: sudo apt install ghostscript
      - name: Change ImageMagick security policy
        run: |
          DQT='"'
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read|write${DQT} pattern=${DQT}PDF${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml

      - name: Convert rnote
        run: |
          docker run -d -it --name alpine alpine:edge sh
          docker exec alpine sh -c \
            'echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories \
            && apk add rnote-cli'

          rsync -rv --include '*/' --include '*.rnote' --exclude '*' --prune-empty-dirs --remove-source-files ./notes ./rnote
          docker cp rnote alpine:/
          find rnote -name "*.rnote" | cut -d . -f 1 | xargs -I {} \
            docker exec alpine rnote-cli export doc --output-file {}.pdf {}.rnote
          docker exec alpine find rnote -name "*.rnote" -delete
          docker cp alpine:/rnote/notes ./uncompressed
          docker exec alpine rm -rf /rnote
          docker rm -f alpine

      - name: Copy pdfs
        run: |
          cd uncompressed
          rsync -av -f"+ */" -f"- *" . ../page/pdf
          find . -name "*.pdf" | cut -d / -f 2- | xargs -I {} \
            cp {} ../page/pdf/{}
          rm -rf $PWD

      - name: Merge
        run: |
          python -m pip install --upgrade pip
          pip install pypdf
          cd page
          python ../scripts/merge.py

      - name: Deploy page
        if: ${{ !env.ACT }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./page
          publish_branch: gh-pages
          enable_jekyll: true
          cname: notes.shirokih.com
          